export const ADD_GATEWAY_SUCCESS = "ADD_GATEWAY_SUCCESS";
export const ADD_GATEWAY_FAIL = "ADD_GATEWAY_FAIL";
export const GET_GATEWAYS_SUCCESS = "GET_GATEWAYS_SUCCESS";
export const GET_GATEWAYS_FAIL = "GET_GATEWAYS_FAIL";
